POST http://localhost:3000/books HTTP/1.1
Content-Type: application/json

 {
    "title": "Brave New World",
    "author": "Aldous Huxley",
    "genre": "Science Fiction",
    "year": 1932,
    "available": false
  }